- repository: isamu-takagi/sync-file-templates
  ref: feat/copy-sync-file-sources
  files:
    - source: CODE_OF_CONDUCT.md
    - source: CONTRIBUTING.md
    - source: DISCLAIMER.md
    - source: LICENSE
    - source: .github/ISSUE_TEMPLATE/bug.yaml
    - source: .github/ISSUE_TEMPLATE/config.yml
    - source: .github/ISSUE_TEMPLATE/task.yaml
    - source: .github/PULL_REQUEST_TEMPLATE.md
    - source: .github/PULL_REQUEST_TEMPLATE/small-change.md
    - source: .github/PULL_REQUEST_TEMPLATE/standard-change.md
    - source: .github/dependabot.yaml
    - source: .github/stale.yml
    - source: .clang-format
    - source: .markdown-link-check.json
    - source: .markdownlint.yaml
    - source: .pre-commit-config-optional.yaml
    - source: .prettierignore
    - source: .prettierrc.yaml
    - source: .yamllint.yaml
    - source: CPPLINT.cfg
    - source: setup.cfg
    - source: .pre-commit-config.yaml
    - source: codecov.yaml
    - source: mkdocs-base.yaml
      dest: mkdocs.yaml
      pre-commands: |
        sd "Autoware Documentation" "Autoware Universe Documentation" {source}
        sd "autoware-documentation" "autoware.universe" {source}
        sd "repo_url: .*" "repo_url: https://github.com/autowarefoundation/autoware.universe" {source}
        sd "/edit/main/docs/" "/edit/main/" {source}
        sd "docs_dir: .*" "docs_dir: ." {source}
        sd "assets/(\w+)" "docs/assets/\$1" {source}
        sd -- \
        "  - macros" \
        "  - macros:
              module_name: mkdocs_macros" {source}
    - source: docs/assets/js/mathjax.js
