name: pre-commit-optional

on:
  pull_request:

jobs:
  pre-commit-optional:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run pre-commit
        uses: isamu-takagi/autoware-github-actions/pre-commit@feat/pre-commit-differential
        with:
          pre-commit-config: .pre-commit-config-optional.yaml
